export {
  PrimaryColor,
  OnPrimaryColor,
  SurfaceColor,
  BackgroundColor,
  OnBackgroundColor,
  OnSurfaceColor,
  ErrorColor,
  SuccessColor,
  WarningColor,
  DividerColor,
  CardBackgroundColor,
  SectionBackgroundColor,
  TrackColor,
  CaptionColor,
  AppColors,
} from './colors'
